import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div
          className="h-[200] bg-black flex justify-center items-center"
        >
          <div className= "flex h-[48]">
          <Image
            aria-hidden
            src="/Rocket.svg"
            alt="Rocket icon"
            width={22}
            height={36}
          />
          <span className="font-inter text-[40px] font-extrabold leading-[48.41px] text-left underline-offset-[from-font] decoration-skip-none">
            <span className="text-textBlue">Todo </span>
            <span className="text-textPurple">App</span>
          </span>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
