import type { Metadata } from "next";
import Image from "next/image";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <div
          className="h-[200] bg-black flex justify-center items-center"
        >
          <div className= "flex h-[48]">
          <Image
            aria-hidden
            src="/Rocket.svg"
            alt="Rocket icon"
            width={22}
            height={36}
          />
          <span className="font-inter text-[40px] font-extrabold leading-[48.41px] text-left underline-offset-[from-font] decoration-skip-none">
            <span className="text-textBlue">Todo </span>
            <span className="text-textPurple">App</span>
          </span>
          </div>
        </div>
        <div className="flex justify-center items-center">
        {children}
        </div>
      </body>
    </html>
  );
}
